import clear from '../../img/weather/clear.svg'
import cloudy from '../../img/weather/cloudy.svg'
import littleRain from '../../img/weather/littleRain.svg'
import littleSnow from '../../img/weather/littleSnow.svg'
import partlyCloudy from '../../img/weather/partlyCloudy.svg'
import rain from '../../img/weather/rain.svg'
import rainSnow from '../../img/weather/rainSnow.svg'
import humid from '../../img/weather/humid.svg'
import snow from '../../img/weather/snow.svg'

export const responseModifiers = {
  weather: {
    clearday: {img: clear, description: 'clear'},
    clearnight: {img: clear, description: 'clear'},
    pcloudyday: {img: partlyCloudy, description: 'partly cloudy'},
    pcloudynight: {img: partlyCloudy, description: 'partly cloudy'},
    mcloudyday: {img: partlyCloudy, description: 'partly cloudy'},
    mcloudynight: {img: partlyCloudy, description: 'partly cloudy'},
    cloudyday: {img: cloudy, description: 'cloudy'},
    cloudynight: {img: cloudy, description: 'cloudy'},
    humidday: {img: humid, description: 'fog'},
    humidnight: {img: humid, description: 'fog'},
    lightrainday: {img: littleRain, description: 'light rain'},
    lightrainnight: {img: littleRain, description: 'light rain'},
    oshowerday: {img: littleRain, description: 'light rain'},
    oshowernight: {img: littleRain, description: 'light rain'},
    ishowerday: {img: littleRain, description: 'light rain'},
    ishowernight: {img: littleRain, description: 'light rain'},
    lightsnowday: {img: littleSnow, description: 'light snow'},
    lightsnownight: {img: littleSnow, description: 'light snow'},
    rainday: {img: rain, description: 'rain'},
    rainnight: {img: rain, description: 'rain'},
    snowday: {img: snow, description: 'snow'},
    snownight: {img: snow, description: 'snow'},
    rainsnowday: {img: rainSnow, description: 'rain snow'},
    rainsnownight: {img: rainSnow, description: 'rain snow'}
  },
  windSpeed: {
    1: 'calm, > 0.3 m/s',
    2: 'light, 0.3-3.4 m/s',
    3: 'moderate, 3.4-8.0 m/s',
    4: 'fresh, 8.0-10.8 m/s',
    5: 'strong, 10.8-17.2 m/s',
    6: 'gale, 17.2-24.5 m/s',
    7: 'storm, 24.5-32.6 m/s',
    8: 'hurricane, > 32.6 m/s'
  },
  cloudcover: {
    1: '0%',
    2: '10%',
    3: '25%',
    4: '40%',
    5: '50%',
    6: '60%',
    7: '75%',
    8: '90%',
    9: '100%'
  },
  monthNames: {
    0: 'Jan',
    1: 'Feb',
    2: 'Mar',
    3: 'Apr',
    4: 'May',
    5: 'Jun',
    6: 'Jul',
    7: 'Aug',
    8: 'Sep',
    9: 'Oct',
    10: 'Nov',
    11: 'Dec'
  }
}

export const resp = {
  "product": "civil",
  "init": "2022111000",
  "dataseries": [
    {"timepoint": 3,"cloudcover": 7,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 6,"rh2m": "73%","wind10m": {"direction": "SE", "speed": 2},"weather": "mcloudynight"},
    {"timepoint": 6,"cloudcover": 6,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 6,"rh2m": "73%","wind10m": {"direction": "SE", "speed": 2},"weather": "mcloudyday"},
    {"timepoint": 9,"cloudcover": 4,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 11,"rh2m": "52%","wind10m": {"direction": "SE", "speed": 2},"weather": "pcloudyday"},
    {"timepoint": 12,"cloudcover": 3,"lifted_index": 10,"prec_type": "none","prec_amount": 0,"temp2m": 14,"rh2m": "45%","wind10m": {"direction": "S", "speed": 3},"weather": "pcloudyday"},
    {"timepoint": 15,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 11,"rh2m": "50%","wind10m": {"direction": "SE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 18,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 9,"rh2m": "65%","wind10m": {"direction": "SE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 21,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 7,"rh2m": "78%","wind10m": {"direction": "SE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 24,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 5,"rh2m": "90%","wind10m": {"direction": "SE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 27,"cloudcover": 4,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 5,"rh2m": "86%","wind10m": {"direction": "SE", "speed": 2},"weather": "pcloudynight"},
    {"timepoint": 30,"cloudcover": 4,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 5,"rh2m": "82%","wind10m": {"direction": "SE", "speed": 2},"weather": "pcloudyday"},
    {"timepoint": 33,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 12,"rh2m": "54%","wind10m": {"direction": "S", "speed": 3},"weather": "clearday"},
    {"timepoint": 36,"cloudcover": 2,"lifted_index": 10,"prec_type": "none","prec_amount": 0,"temp2m": 14,"rh2m": "43%","wind10m": {"direction": "S", "speed": 3},"weather": "clearday"},
    {"timepoint": 39,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 11,"rh2m": "56%","wind10m": {"direction": "S", "speed": 2},"weather": "clearnight"},
    {"timepoint": 42,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 8,"rh2m": "77%","wind10m": {"direction": "SE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 45,"cloudcover": 4,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 7,"rh2m": "88%","wind10m": {"direction": "SE", "speed": 2},"weather": "pcloudynight"},
    {"timepoint": 48,"cloudcover": 6,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 6,"rh2m": "94%","wind10m": {"direction": "SE", "speed": 2},"weather": "mcloudynight"},
    {"timepoint": 51,"cloudcover": 9,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 7,"rh2m": "87%","wind10m": {"direction": "W", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 54,"cloudcover": 9,"lifted_index": 15,"prec_type": "none","prec_amount": 0,"temp2m": 8,"rh2m": "85%","wind10m": {"direction": "NW", "speed": 2},"weather": "cloudyday"},
    {"timepoint": 57,"cloudcover": 9,"lifted_index": 10,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "78%","wind10m": {"direction": "N", "speed": 2},"weather": "cloudyday"},
    {"timepoint": 60,"cloudcover": 9,"lifted_index": 10,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "88%","wind10m": {"direction": "N", "speed": 2},"weather": "cloudyday"},
    {"timepoint": 63,"cloudcover": 9,"lifted_index": 10,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "95%","wind10m": {"direction": "N", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 66,"cloudcover": 9,"lifted_index": 10,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "90%","wind10m": {"direction": "N", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 69,"cloudcover": 9,"lifted_index": 10,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "87%","wind10m": {"direction": "N", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 72,"cloudcover": 9,"lifted_index": 10,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "85%","wind10m": {"direction": "N", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 75,"cloudcover": 9,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 8,"rh2m": "76%","wind10m": {"direction": "N", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 78,"cloudcover": 7,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 7,"rh2m": "80%","wind10m": {"direction": "NW", "speed": 2},"weather": "mcloudyday"},
    {"timepoint": 81,"cloudcover": 5,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 11,"rh2m": "63%","wind10m": {"direction": "NW", "speed": 2},"weather": "pcloudyday"},
    {"timepoint": 84,"cloudcover": 5,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 12,"rh2m": "55%","wind10m": {"direction": "NW", "speed": 2},"weather": "pcloudyday"},
    {"timepoint": 87,"cloudcover": 7,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 10,"rh2m": "61%","wind10m": {"direction": "NW", "speed": 2},"weather": "mcloudynight"},
    {"timepoint": 90,"cloudcover": 7,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 8,"rh2m": "70%","wind10m": {"direction": "W", "speed": 2},"weather": "mcloudynight"},
    {"timepoint": 93,"cloudcover": 5,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 7,"rh2m": "79%","wind10m": {"direction": "W", "speed": 2},"weather": "pcloudynight"},
    {"timepoint": 96,"cloudcover": 3,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 6,"rh2m": "79%","wind10m": {"direction": "SW", "speed": 2},"weather": "pcloudynight"},
    {"timepoint": 99,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 6,"rh2m": "83%","wind10m": {"direction": "W", "speed": 2},"weather": "clearnight"},
    {"timepoint": 102,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 6,"rh2m": "75%","wind10m": {"direction": "W", "speed": 2},"weather": "clearday"},
    {"timepoint": 105,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 11,"rh2m": "54%","wind10m": {"direction": "W", "speed": 2},"weather": "clearday"},
    {"timepoint": 108,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 13,"rh2m": "44%","wind10m": {"direction": "NW", "speed": 3},"weather": "clearday"},
    {"timepoint": 111,"cloudcover": 3,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 10,"rh2m": "55%","wind10m": {"direction": "NW", "speed": 2},"weather": "pcloudynight"},
    {"timepoint": 114,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "66%","wind10m": {"direction": "NW", "speed": 2},"weather": "clearnight"},
    {"timepoint": 117,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 7,"rh2m": "74%","wind10m": {"direction": "N", "speed": 2},"weather": "clearnight"},
    {"timepoint": 120,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 6,"rh2m": "87%","wind10m": {"direction": "N", "speed": 2},"weather": "clearnight"},
    {"timepoint": 123,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 5,"rh2m": "93%","wind10m": {"direction": "N", "speed": 2},"weather": "humidnight"},
    {"timepoint": 126,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 5,"rh2m": "93%","wind10m": {"direction": "N", "speed": 2},"weather": "humidday"},
    {"timepoint": 129,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "70%","wind10m": {"direction": "NE", "speed": 2},"weather": "clearday"},
    {"timepoint": 132,"cloudcover": 2,"lifted_index": 10,"prec_type": "none","prec_amount": 1,"temp2m": 11,"rh2m": "60%","wind10m": {"direction": "NE", "speed": 2},"weather": "clearday"},
    {"timepoint": 135,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 9,"rh2m": "70%","wind10m": {"direction": "NE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 138,"cloudcover": 3,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 8,"rh2m": "78%","wind10m": {"direction": "NE", "speed": 2},"weather": "pcloudynight"},
    {"timepoint": 141,"cloudcover": 9,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 7,"rh2m": "78%","wind10m": {"direction": "NE", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 144,"cloudcover": 9,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 5,"rh2m": "72%","wind10m": {"direction": "NE", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 147,"cloudcover": 9,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 4,"rh2m": "67%","wind10m": {"direction": "NE", "speed": 2},"weather": "cloudynight"},
    {"timepoint": 150,"cloudcover": 9,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 4,"rh2m": "50%","wind10m": {"direction": "NE", "speed": 2},"weather": "cloudyday"},
    {"timepoint": 153,"cloudcover": 8,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 8,"rh2m": "45%","wind10m": {"direction": "E", "speed": 3},"weather": "cloudyday"},
    {"timepoint": 156,"cloudcover": 4,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 10,"rh2m": "42%","wind10m": {"direction": "E", "speed": 3},"weather": "pcloudyday"},
    {"timepoint": 159,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 7,"rh2m": "55%","wind10m": {"direction": "E", "speed": 2},"weather": "clearnight"},
    {"timepoint": 162,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 4,"rh2m": "62%","wind10m": {"direction": "E", "speed": 2},"weather": "clearnight"},
    {"timepoint": 165,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 2,"rh2m": "72%","wind10m": {"direction": "E", "speed": 2},"weather": "clearnight"},
    {"timepoint": 168,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 1,"rh2m": "82%","wind10m": {"direction": "E", "speed": 2},"weather": "clearnight"},
    {"timepoint": 171,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 0,"rh2m": "82%","wind10m": {"direction": "E", "speed": 2},"weather": "clearnight"},
    {"timepoint": 174,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": -1,"rh2m": "75%","wind10m": {"direction": "E", "speed": 2},"weather": "clearday"},
    {"timepoint": 177,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 4,"rh2m": "46%","wind10m": {"direction": "SE", "speed": 3},"weather": "clearday"},
    {"timepoint": 180,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 7,"rh2m": "39%","wind10m": {"direction": "SE", "speed": 3},"weather": "clearday"},
    {"timepoint": 183,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 4,"rh2m": "36%","wind10m": {"direction": "SE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 186,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 1,"rh2m": "45%","wind10m": {"direction": "SE", "speed": 2},"weather": "clearnight"},
    {"timepoint": 189,"cloudcover": 2,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": 0,"rh2m": "48%","wind10m": {"direction": "E", "speed": 2},"weather": "clearnight"},
    {"timepoint": 192,"cloudcover": 1,"lifted_index": 15,"prec_type": "none","prec_amount": 1,"temp2m": -1,"rh2m": "50%","wind10m": {"direction": "E", "speed": 2},"weather": "clearnight"}
  ]
}
